// src/components/layout/MobileNavBar.svelte
<script lang="ts">
  let expanded = false;
</script>

<div class="flex-grow md:hidden" />

<!-- Menu Button -->
<div class="hover:cursor-pointer md:hidden" on:mousedown={() => (expanded = !expanded)}>
  <span class="icon-[mdi--menu] text-2xl text-white" />
</div>

<!-- Mobile Navigation -->
<!-- TODO: Implement -->

// src/components/layout/MobileNavBar.tsx
"use client";

import type React from "react";
import { useState } from "react";

export const MobileNavBar: React.FC = () => {
  const [expanded, setExpanded] = useState(false);

  return (
    <>
      <div className="flex-grow md:hidden" />

      <button type="button" className="hover:cursor-pointer md:hidden" onMouseDown={() => setExpanded(!expanded)}>
        <span className="icon-[mdi--menu] text-2xl text-white" />
      </button>
    </>
  );
};
