// src/components/layout/NavBar.svelte
<script lang="ts">
  import Image from '$components/base/Image.svelte';
  import { FEATURED_ARTIST } from '$lib/data/commissions';
  import DesktopNavBar from './DesktopNavBar.svelte';
</script>

<div class="flex h-24 border-b border-b-white/10">
  <div class="my-auto flex w-full flex-row items-center">
    <!-- Avatar -->
    <Image maxWidth="5vw" class="aspect-square h-11 w-11 rounded-xl object-cover object-top" picture={FEATURED_ARTIST.commission.images[0]} alt="Logo" />
    <div class="flex-grow md:hidden" />

    <!-- Navigation -->
    <DesktopNavBar />
    <!-- <MobileNavBar /> -->
  </div>
</div>

// src/components/layout/navbar.tsx
import Image from "next/image";
import Link from "next/link";
import type React from "react";
import { FEATURED_ARTIST, getArtRefImage } from "@/lib/content";
import { DesktopNavBar } from "./desktop-nav-bar";

export const Navbar: React.FC = () => (
  <div className="flex h-24 border-b border-b-white/10">
    <div className="my-auto flex w-full flex-row items-center">
      <Link href="/">
        <Image
          src={getArtRefImage(FEATURED_ARTIST)}
          alt="Logo"
          width={44}
          height={44}
          className="aspect-square size-11 rounded-xl object-cover object-top"
        />
      </Link>

      <div className="flex-grow md:hidden" />

      <DesktopNavBar />
    </div>
  </div>
);
