// src/components/interactive/CallToAction.svelte
<script lang="ts">
  import GradientBackground from '$components/base/GradientBackground.svelte';
  import Image from '$components/base/Image.svelte';
  import { getLinkProps } from '$lib/util/html';
  import type { Picture } from 'imagetools-core';

  export let href: string;
  export let picture: Picture | undefined;

  export let picMaxWidth = '100%';
</script>

<a {href} {...getLinkProps(href)} class="relative flex overflow-clip rounded-xl border border-white/25 transition-all hover:scale-[101%] hover:shadow-xl">
  <div class="absolute inset-0">
    <!-- Picture -->
    {#if picture}
      <Image {picture} class="h-full w-full object-cover object-top" alt="Cover" maxWidth={picMaxWidth} />
      <div class="absolute left-0 top-0 z-[1] h-full w-full bg-gradient-to-b from-transparent to-black/80" />
    {:else}
      <!-- Cool ass gradient instead -->
      <GradientBackground class="opacity-50" />
    {/if}
  </div>

  <!-- Headings -->
  <div class="relative z-[2]">
    <slot />
  </div>
</a>

// src/components/interactive/CallToAction.tsx
import Image, { type StaticImageData } from "next/image";
import type React from "react";
import { GradientBackground } from "@/components/base/GradientBackground";
import { getLinkProps } from "@/lib/util/html";

type CallToActionProps = {
  href: string;
  picture?: {
    src: StaticImageData;
    alt?: string;
  };
  picMaxWidth?: string;
} & React.PropsWithChildren;

export const CallToAction: React.FC<CallToActionProps> = ({ href, picture, picMaxWidth = "100%", children }) => {
  const linkProps = getLinkProps(href);

  return (
    <a
      href={href}
      {...linkProps}
      className="relative flex overflow-clip rounded-xl border border-white/25 transition-all hover:scale-[101%] hover:shadow-xl"
    >
      <div className="absolute inset-0">
        {picture ? (
          <>
            <Image
              src={picture.src}
              alt={picture.alt || "Cover"}
              fill
              className="h-full w-full object-cover object-top"
              style={{ maxWidth: picMaxWidth }}
            />
            <div className="absolute top-0 left-0 z-[1] h-full w-full bg-gradient-to-b from-transparent to-black/80" />
          </>
        ) : (
          <GradientBackground className="opacity-50" />
        )}
      </div>

      <div className="relative z-[2]">{children}</div>
    </a>
  );
};
