// src/components/interactive/link.tsx
import type { Route } from "next";
import Image, { type StaticImageData } from "next/image";
import Link from "next/link";
import type React from "react";
import { MdArrowBack, MdArrowOutward } from "react-icons/md";
import { cn } from "@/lib/utils";

type SiteLinkProps = {
  href?: Route;
  picture?: {
    src: StaticImageData;
    alt?: string;
  };
  type?: "default" | "back";
  picClass?: string;
} & React.PropsWithChildren &
  Omit<React.ComponentProps<typeof Link>, "href">;

export const SiteLink: React.FC<SiteLinkProps> = ({
  href,
  picture,
  type = "default",
  picClass = "size-11 rounded-xl",
  className,
  children,
  ...props
}) => {
  const Comp = href ? Link : "span";
  return (
    <Comp {...props} href={href ?? "#"} className={cn("group flex flex-row items-center gap-2", className)}>
      {type === "back" && <MdArrowBack className="size-5 group-hover:animate-pulse" />}
      {picture && <Image src={picture.src} alt={picture.alt ?? "Logo"} width={44} height={44} className={picClass} />}
      <h1 className={type === "back" ? "group-hover:animate-pulse" : ""}>{children}</h1>
      {type === "default" && <MdArrowOutward className="size-5" />}
    </Comp>
  );
};

// src/components/interactive/Link.svelte
<script lang="ts">
  import type { Picture } from 'imagetools-core';
  import Image from '$components/base/Image.svelte';
  import { getLinkProps } from '$lib/util/html';

  export let href: string | undefined;
  export let picture: Picture | undefined = undefined;
  export let style: 'default' | 'back' = 'default';

  export let picAlt = 'Logo';
  export let picClass = 'h-11 w-11 rounded-xl';

  let className = '';
  // noinspection ReservedWordAsName
  export { className as class };
</script>

<a {href} {...getLinkProps(href)} class="group flex flex-row items-center gap-2 {className}">
  {#if style === 'back'}
    <span class="icon-[material-symbols--arrow-back] h-5 w-5 group-hover:animate-pulse" />
  {/if}

  {#if picture}
    <Image width="30px" height="30px" class={picClass} {picture} alt={picAlt} />
  {/if}

  <h1 class:group-hover:animate-pulse={style === 'back'}><slot /></h1>
  {#if href && style === 'default'}
    <span class="icon-[material-symbols--arrow-outward] h-5 w-5" />
  {/if}
</a>
