// src/components/home/Project.svelte
<script lang="ts">
  import { LANGUAGES, type Project } from '$lib/data/projects';

  export let project: Project;

  // Fetch the language
  const language = LANGUAGES[project?.language];
</script>

<a
  href={project.url}
  target="_blank"
  rel="noopener noreferrer"
  class="hoverable hoverable-card flex flex-col gap-3 border border-white/10 bg-gradient-to-b from-white/[2.5%] p-6 transition-all duration-300 hover:scale-[101%] hover:to-white/[5%] hover:shadow-md"
>
  <div class="flex flex-row items-center">
    <!-- Language icon -->
    <span class="{language.icon} h-5 w-5" />

    <!-- Language name -->
    <span class="ml-2 opacity-75">{language.name}</span>

    <!-- Year -->
    <span class="ml-auto opacity-75">{project.year ?? 'Current'}</span>
  </div>

  <div class="flex flex-row items-center">
    <!-- Project name -->
    <h1 class="text-2xl font-bold">{project.name}</h1>

    <!-- Arrow Icon -->
    <span class="icon-[material-symbols--arrow-outward] ml-4 h-6 w-6" />
  </div>

  <span class="opacity-75">{project.description}</span>
</a>

// src/components/home/Project.tsx
import type React from "react";
import { LANGUAGES, type Project as ProjectType } from "@/lib/data/projects";

type ProjectProps = {
  project: ProjectType;
};

export const Project: React.FC<ProjectProps> = ({ project }) => {
  const language = LANGUAGES[project.language];

  return (
    <a
      href={project.url}
      target="_blank"
      rel="noopener noreferrer"
      className="hoverable hoverable-card flex flex-col gap-3 border border-white/10 bg-gradient-to-b from-white/[2.5%] p-6 transition-all duration-300 hover:scale-[101%] hover:to-white/[5%] hover:shadow-md"
    >
      <div className="flex flex-row items-center">
        <span className={`${language.icon} h-5 w-5`} />
        <span className="ml-2 opacity-75">{language.name}</span>
        <span className="ml-auto opacity-75">{project.year ?? "Current"}</span>
      </div>

      <div className="flex flex-row items-center">
        <h1 className="font-bold text-2xl">{project.name}</h1>
        <span className="icon-[material-symbols--arrow-outward] ml-4 h-6 w-6" />
      </div>

      <span className="opacity-75">{project.description}</span>
    </a>
  );
};
