// src/components/home/TwinklingStar.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  // Randomly move the star around by tweening its x and y coordinates
  // in an offset from its original position, using a sine wave to
  // create a smooth, natural motion
  let data = { x: 0, y: 0, size: 0, opacity: 0 };

  // Create a random offset
  const offset = Math.random() * 5;

  // Create a random speed
  // 5 - 10
  let speed = 0;

  // Signed directions
  let directions = [-1, 1];

  const render = () => {
    // Update the completion status
    if (speed === 0 || data.opacity < 0.001) {
      speed = Math.random() * 15 + 5;
      directions = [Math.random() * 2 - 1, Math.random() * 2 - 1];
    }

    // Update the data
    data = {
      x: directions[0] * Math.sin(Date.now() / 1000 + offset) * speed,
      y: directions[1] * Math.sin(Date.now() / 1000 + offset) * speed,
      size: Math.sin(Date.now() / 1000 + offset) * speed + 20,
      opacity: Math.sin(Date.now() / 1000 + offset) * 0.5 + 0.5,
    };

    // Request the next frame
    requestAnimationFrame(render);
  };

  onMount(() => requestAnimationFrame(render));
</script>

<div class="relative">
  <div class="absolute" style="left: {data.x}px; top: {data.y}px; width: {data.size}px; height: {data.size}px; opacity: {data.opacity};">
    <slot />
  </div>
</div>

// src/components/home/twinkling-star.tsx
"use client";

import type React from "react";
import { useEffect, useRef, useState } from "react";

export const TwinklingStar: React.FC<React.PropsWithChildren> = ({ children }) => {
  const [data, setData] = useState({ x: 0, y: 0, size: 0, opacity: 0 });
  const animationRef = useRef<number | undefined>(undefined);
  const offsetRef = useRef<number>(0);
  const speedRef = useRef<number>(0);
  const directionsRef = useRef<number[]>([-1, 1]);

  useEffect(() => {
    const render = () => {
      if (speedRef.current === 0 || data.opacity < 0.001) {
        speedRef.current = Math.random() * 15 + 5;
        directionsRef.current = [Math.random() * 2 - 1, Math.random() * 2 - 1];
      }

      const now = Date.now() / 1000;
      const offset = offsetRef.current;

      setData({
        x: (directionsRef.current?.[0] ?? 0) * Math.sin(now + offset) * speedRef.current,
        y: (directionsRef.current?.[1] ?? 0) * Math.sin(now + offset) * speedRef.current,
        size: Math.sin(now + offset) * speedRef.current + 20,
        opacity: Math.sin(now + offset) * 0.5 + 0.5,
      });

      animationRef.current = requestAnimationFrame(render);
    };

    animationRef.current = requestAnimationFrame(render);

    return () => {
      if (animationRef.current) {
        cancelAnimationFrame(animationRef.current);
      }
    };
  }, [data.opacity]);

  return (
    <div className="relative">
      <div
        className="absolute"
        style={{
          left: `${data.x}px`,
          top: `${data.y}px`,
          width: `${data.size}px`,
          height: `${data.size}px`,
          opacity: data.opacity,
        }}
      >
        {children}
      </div>
    </div>
  );
};
