// src/app/art/[artist]/[slug]/page.tsx
import type { Metadata, Route } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { FaTwitter } from "react-icons/fa";
import { IconLink } from "@/components/interactive/IconLink";
import { SiteLink } from "@/components/interactive/Link";
import { allArtists } from "@/lib/content";

export async function generateStaticParams() {
  return allArtists.flatMap((artist) =>
    artist.commissions.map((commission) => ({ artist: artist.slug, slug: commission.slug }))
  );
}

export async function generateMetadata({ params }: PageProps<"/art/[artist]/[slug]">): Promise<Metadata> {
  const { artist: artistSlug, slug } = await params;
  const artist = allArtists.find((a) => a.slug === artistSlug);
  if (!artist) notFound();

  const commission = artist.commissions.find((c) => c.slug === slug);
  if (!commission) notFound();

  return {
    title: commission.title,
    description: commission.description || "",
    openGraph: {
      images: commission.images.length > 0 ? [{ url: commission.images[0]!.src, alt: "Illustration" }] : [],
    },
    twitter: {
      card: "summary_large_image",
      images: commission.images.length > 0 ? [commission.images[0]!.src] : [],
    },
  };
}

export default async function CommissionPage({ params }: PageProps<"/art/[artist]/[slug]">) {
  const { artist: artistSlug, slug } = await params;
  const artist = allArtists.find((a) => a.slug === artistSlug);
  if (!artist) notFound();

  const commission = artist.commissions.find((c) => c.slug === slug);
  if (!commission) notFound();

  return (
    <div className="layout-container pt-40 pb-36">
      <div className="flex flex-col gap-6">
        <SiteLink type="back" href="/art" className="opacity-50">
          Back to all commissions
        </SiteLink>
        <SiteLink
          href={artist.link as Route}
          picture={artist.avatar ? { src: artist.avatar } : undefined}
          className="text-white/50"
          picClass="size-6 rounded-md"
        >
          By {artist.name}
        </SiteLink>

        {/* Title */}
        <h1 className="font-bold text-5xl">{commission.title}</h1>

        {/* Description */}
        {commission.description && <p className="opacity-50">{commission.description}</p>}

        {/* Links */}
        {commission.links && commission.links.length > 0 && (
          <div className="flex flex-row gap-4">
            {commission.links.map((link) => (
              <IconLink key={link.href} href={link.href as Route} icon={FaTwitter}>
                {link.text}
              </IconLink>
            ))}
          </div>
        )}

        {/* Images */}
        <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
          {commission.images.map((image, idx) => (
            // biome-ignore lint/suspicious/noArrayIndexKey: Needed
            <div key={idx} className="flex size-full flex-col items-center justify-center bg-primary-700">
              <Image src={image} alt={commission.title} className="rounded-md object-cover object-center" />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// src/routes/art/[artist]/[slug]/+page.svelte
<script lang="ts">
  import Image from '$components/base/Image.svelte';
  import IconLink from '$components/interactive/IconLink.svelte';
  import Link from '$components/interactive/Link.svelte';
  import Seo from '$components/seo/Seo.svelte';
  import type { PageData } from './$types';

  export let data: PageData;
</script>

<Seo
  title={data.commission.title}
  description={data.commission.description || ''}
  twitterImage={{ url: data.commission.images[0].fallback.src, alt: 'Illustration' }}
/>

<div class="layout-container pt-40 pb-36">
  <div class="flex flex-col gap-6">
    <Link style="back" href="/art" class="opacity-50">Back to all commissions</Link>
    <Link href={data.artist.link} picture={data.artist.avatar} class="text-white/50" picClass="h-6 w-6 rounded-md">
      By {data.artist.name}
    </Link>

    <!-- Title -->
    <h1 class="text-5xl font-bold">{data.commission.title}</h1>

    <!-- Description -->
    {#if data.commission.description}
      <p class="opacity-50">{data.commission.description}</p>
    {/if}

    <!-- Links -->
    {#if data.commission.links}
      <div class="flex flex-row gap-4">
        {#each data.commission.links as link}
          <IconLink href={link.href} icon="icon-[mdi--twitter]">{link.text}</IconLink>
        {/each}
      </div>
    {/if}

    <!-- Images -->
    <div class="grid grid-cols-1 gap-4 md:grid-cols-3">
      {#each data.commission.images as image}
        <Image maxWidth="33vw" picture={image} class="rounded-md object-cover object-center" alt={data.commission.title} />
      {/each}
    </div>
  </div>
</div>
