// src/routes/blog/+page.svelte
<script lang="ts">
  import Seo from '$components/seo/Seo.svelte';
  import type { PageData } from './$types';

  export let data: PageData;
</script>

<Seo title="Blog" slug="/blog" />

<div class="layout-container pt-40 pb-36">
  <div class="flex flex-col gap-3">
    <p class="text-2xl font-medium"><span class="pr-4">📖</span> Blog</p>
    <h1 class="text-5xl font-bold leading-[1.8] sm:text-5xl sm:leading-[1.8]">My thoughts on software development, web development, and more.</h1>
  </div>

  <div class="flex flex-col pt-32">
    <!-- TODO: Cleanup, tags -->
    {#each data.posts as post}
      <a href="/blog/{post.slug}" class="flex flex-row items-center border-b border-b-white/[15%]">
        <!-- TODO: Make the below a component -->
        <div class="flex grow flex-col gap-3 py-9">
          <!-- Date -->
          <span
            >{new Date(post.metadata.date).toLocaleDateString('en-US', {
              year: 'numeric',
              month: 'long',
              day: 'numeric',
            })}</span
          >

          <!-- Title -->
          <h2 class="text-2xl font-bold">{post.metadata.title}</h2>

          <!-- Excerpt -->
          <span class="opacity-50">{post.metadata.description ?? 'Take a read :)'}</span>
        </div>

        <img src={post.metadata.cover} alt="" class="aspect-video h-32 rounded-xl border border-white/25 object-cover" />
      </a>
    {/each}
  </div>
</div>

// src/app/blog/page.tsx
import { getBlogPosts } from '@/lib/content'
import Image from 'next/image'
import Link from 'next/link'

export default function BlogPage() {
  const posts = getBlogPosts()

  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-4xl font-bold mb-8">Blog</h1>
      
      <div className="space-y-6">
        {posts.map((post) => (
          <article key={post._meta.path} className="border border-white/10 rounded-lg p-6 hover:bg-white/5 transition-colors">
            <div className="flex gap-6">
              {post.cover && (
                <div className="w-48 h-32 relative overflow-hidden rounded-lg flex-shrink-0">
                  <Image
                    src={post.cover}
                    alt={post.title}
                    fill
                    className="object-cover"
                  />
                </div>
              )}
              
              <div className="flex-grow">
                <a href={`/blog/${post._meta.path.split('/').pop()?.replace('.md', '')}`}>
                  <h2 className="text-2xl font-bold mb-2 hover:text-blue-400 transition-colors">
                    {post.title}
                  </h2>
                </a>
                
                <p className="text-gray-400 mb-3">{post.description}</p>
                
                <time className="text-sm text-gray-500">
                  {new Date(post.date).toLocaleDateString('en-US', {
                    year: 'numeric',
                    month: 'long',
                    day: 'numeric'
                  })}
                </time>
              </div>
            </div>
          </article>
        ))}
      </div>
    </div>
  )
}
